{
    'name': 'LINE Payment & Slip Auto-Verify Integration',
    'version': '19.0.1.0.1',
    'category': 'Accounting/Accounting',
    'summary': 'Automate invoice payments via LINE with Slip Verification, Dynamic QR Codes, and Auto-Reconciliation',
    'author': 'AACC',
    'website': 'https://aacc-th.com',
    'support': 'https://aacc-th.com/support',
    'license': 'OPL-1',
    'price': 27.07,
    'currency': 'USD',
    'depends': ['account', 'mail', 'base', 'website'],
    'data': [
        'views/res_config_settings_views.xml',
        'views/res_partner_views.xml',
        'views/line_login_templates.xml',
        'views/account_move_views.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
